USE GD2C2022
GO
/*DROP FOREIGN KEYS*/

/*IF OBJECT_ID('M_AL_CUBO.FK_XXXX', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.TABLA DROP CONSTRAINT FK_XXX
GO*/

IF OBJECT_ID('M_AL_CUBO.FK_COMPRA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.DESCUENTO_COMPRA DROP CONSTRAINT FK_COMPRA_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_COMPRA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.DESCUENTO_COMPRA DROP CONSTRAINT FK_COMPRA_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_PROVEEDOR_LOCALIDAD_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.DESCUENTO_COMPRA DROP CONSTRAINT FK_PROVEEDOR_LOCALIDAD_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_PROVINCIA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.LOCALIDAD DROP CONSTRAINT FK_PROVINCIA_ID
GO


IF OBJECT_ID('M_AL_CUBO.FK_CLIENTE_LOCALIDAD_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.CLIENTE DROP CONSTRAINT FK_CLIENTE_LOCALIDAD_ID
GO


IF OBJECT_ID('M_AL_CUBO.FK_PROVEEDOR_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.COMPRA DROP CONSTRAINT FK_PROVEEDOR_ID
GO


IF OBJECT_ID('M_AL_CUBO.FK_COMPRA_MEDIO_PAGO', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.COMPRA DROP CONSTRAINT FK_COMPRA_MEDIO_PAGO
GO


IF OBJECT_ID('M_AL_CUBO.FK_DESCUENTO_COMPRA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.COMPRA DROP CONSTRAINT FK_DESCUENTO_COMPRA_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_PRODUCTO_X__VAR_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE_X_COMPRA DROP CONSTRAINT FK_PRODUCTO_X__VAR_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_COMPRA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE_X_COMPRA DROP CONSTRAINT FK_COMPRA_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_PRODUCTO_VARIANTE_CODIGO', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.TIPO_VARIANTE DROP CONSTRAINT FK_PRODUCTO_VARIANTE_CODIGO
GO

IF OBJECT_ID('M_AL_CUBO.FK_PRODUCTO_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE DROP CONSTRAINT FK_PRODUCTO_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_TIPO_VARIANTE_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE DROP CONSTRAINT FK_TIPO_VARIANTE_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_VENTA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE_X_VENTA DROP CONSTRAINT FK_PRODUCTO_VENTA_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_MATERIAL_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.PRODUCTO DROP CONSTRAINT FK_MATERIAL_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_MARCA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.PRODUCTO DROP CONSTRAINT FK_MARCA_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_CATEGORIA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.PRODUCTO DROP CONSTRAINT FK_CATEGORIA_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_MEDIO_PAGO_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.MEDIO_PAGO_VENTAS DROP CONSTRAINT FK_MEDIO_PAGO_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_VENTA_MEDIO_PAGO_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.VENTA DROP CONSTRAINT FK_VENTA_MEDIO_PAGO_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_VENTA_CLIENTE_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.VENTA DROP CONSTRAINT FK_VENTA_CLIENTE_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_VENTA_CANAL_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.VENTA DROP CONSTRAINT FK_VENTA_CANAL_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_MEDIO_ENVIO_LOC_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.VENTA DROP CONSTRAINT FK_MEDIO_ENVIO_LOC_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_DESCUENTO_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.DESCUENTO_X_VENTA DROP CONSTRAINT FK_DESCUENTO_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_VENTA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.DESCUENTO_X_VENTA DROP CONSTRAINT FK_VENTA_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_LOCALIDAD_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.MEDIO_ENVIO_X_LOCALIDAD DROP CONSTRAINT FK_LOCALIDAD_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_MEDIO_ENIVO_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.MEDIO_ENVIO_X_LOCALIDAD DROP CONSTRAINT FK_MEDIO_ENVIO_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_CUPON_TIPO_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.CUPON DROP CONSTRAINT FK_CUPON_TIPO_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_VENTA_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.CUPON_X_VENTA DROP CONSTRAINT FK_VENTA_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_CUPON_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.CUPON_X_VENTA DROP CONSTRAINT FK_CUPON_ID
GO

IF OBJECT_ID('M_AL_CUBO.FK_CANAL_ID', 'F') IS NOT NULL
  ALTER TABLE M_AL_CUBO.CANAL_VENTA DROP CONSTRAINT FK_CANAL_ID
GO

/*DROP TABLAS*/

/*IF OBJECT_ID('M_AL_CUBO.NOMBRE_TABLA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.NOMBRE_TABLA
GO*/

IF OBJECT_ID('M_AL_CUBO.DESCUENTO_COMPORA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.DESCUENTO_COMPRA
GO

IF OBJECT_ID('M_AL_CUBO.PROVEEDOR', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.PROVEEDOR
GO

IF OBJECT_ID('M_AL_CUBO.LOCALIDAD', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.LOCALIDAD
GO

IF OBJECT_ID('M_AL_CUBO.PROVINCIA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.PROVINCIA
GO

IF OBJECT_ID('M_AL_CUBO.MEDIO_PAGO', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.MEDIO_PAGO
GO

IF OBJECT_ID('M_AL_CUBO.COMPRA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.COMPRA
GO

IF OBJECT_ID('M_AL_CUBO.PRODUCTO_X_VARIANTE_X_COMPRA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE_X_COMPRA
GO

IF OBJECT_ID('M_AL_CUBO.PRODUCTO_X_VARIANTE_X_VENTA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE_X_VENTA
GO

IF OBJECT_ID('M_AL_CUBO.VARIANTE', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.VARIANTE
GO

IF OBJECT_ID('M_AL_CUBO.TIPO_VARIANTE', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.TIPO_VARIANTE
GO

IF OBJECT_ID('M_AL_CUBO.PRODUCTO_X_VARIANTE', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE
GO

IF OBJECT_ID('M_AL_CUBO.PRODUCTO', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.PRODUCTO
GO

IF OBJECT_ID('M_AL_CUBO.MEDIO_PAGO_VENTAS', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.MEDIO_PAGO_VENTAS
GO

IF OBJECT_ID('M_AL_CUBO.CLIENTE', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.CLIENTE
GO

IF OBJECT_ID('M_AL_CUBO.CATEGORIA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.CATEGORIA
GO

IF OBJECT_ID('M_AL_CUBO.MARCA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.MARCA
GO

IF OBJECT_ID('M_AL_CUBO.MATERIAL', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.MATERIAL
GO

IF OBJECT_ID('M_AL_CUBO.MEDIO_ENVIO_X_LOCALIDAD', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.MEDIO_ENVIO_X_LOCALIDAD
GO

IF OBJECT_ID('M_AL_CUBO.VENTA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.VENTA
GO

IF OBJECT_ID('M_AL_CUBO.DESCUENTO_X_VENTA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.DESCUENTO_X_VENTA
GO

IF OBJECT_ID('M_AL_CUBO.DESCUENTO', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.DESCUENTO
GO

IF OBJECT_ID('M_AL_CUBO.CUPON', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.CUPON
GO

IF OBJECT_ID('M_AL_CUBO.CUPON_X_VENTA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.CUPON_X_VENTA
GO

IF OBJECT_ID('M_AL_CUBO.CANAL_VENTA', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.CANAL_VENTA
GO

IF OBJECT_ID('M_AL_CUBO.TIPO_CUPON', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.TIPO_CUPON
GO

IF OBJECT_ID('M_AL_CUBO.CANAL', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.CANAL
GO

IF OBJECT_ID('M_AL_CUBO.MEDIO_ENVIO', 'U') IS NOT NULL
    DROP TABLE M_AL_CUBO.MEDIO_ENVIO
GO

/*DROP FUNCIONES*/

IF OBJECT_ID('M_AL_CUBO.NOMBRE_FUNCION') IS NOT NULL
	DROP FUNCTION M_AL_CUBO.NOMBRE_FUNCION
GO



/*DROP PROCEDURES*/
/*
IF OBJECT_ID('M_AL_CUBO.MIGRAR_DESCUENTO_COMPRA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_NOMBRETABLA
GO  */

IF OBJECT_ID('M_AL_CUBO.MIGRAR_PROVEEDOR') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_PROVEEDOR
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_LOCALIDAD') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_LOCALIDAD
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_PROVINCIA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_PROVINCIA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_MEDIO_PAGO') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_MEDIO_PAGO
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_COMPRA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_COMPRA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_PRODUCTO_X_VARIANTE_COMPRA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_PRODUCTO_X_VARIANTE_COMPRA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_TIPO_VARIANTE') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_TIPO_VARIANTE
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_VARIANTE') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_VARIANTE
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_PRODUCTO_X_VARIANTE') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_PRODUCTO_X_VARIANTE
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_PRODUCTO') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_PRODUCTO
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_MEDIO_PAGO_VENTAS') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_MEDIO_PAGO_VENTAS
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_CLIENTE') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_CLIENTE
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_PRODUCTO_X_VARIANTE_X_VENTA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_PRODUCTO_X_VARIANTE_X_VENTA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_CATEGORIA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_CATEGORIA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_MARCA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_MARCA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_MATERIAL') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_MATERIAL
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_VENTA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_VENTA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_DESCUENTO_X_VENTA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_DESCUENTO_X_VENTA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_DESCUENTO') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_DESCUENTO
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_MEDIO_ENVIO_X_LOCALIDAD') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_MEDIO_ENVIO_X_LOCALIDAD
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_MEDIO_ENVIO') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_MEDIO_ENVIO
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_CANAL_VENTA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_CANAL_VENTA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_CUPON_X_VENTA') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_CUPON_X_VENTA
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_CUPON') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_CUPON
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_TIPO_CUPON') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_TIPO_CUPON
GO  

IF OBJECT_ID('M_AL_CUBO.MIGRAR_CANAL') IS NOT NULL
  DROP PROCEDURE M_AL_CUBO.MIGRAR_CANAL
GO  

/*DROP ESQUEMA*/

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'M_AL_CUBO')
  DROP SCHEMA M_AL_CUBO
GO

/*CREAR ESQUEMA*/

CREATE SCHEMA M_AL_CUBO
GO

/*CREAR TABLAS*/

CREATE TABLE DESCUENTO_COMPRA (
  COMPRA_DESCUENTO_ID INT,
  COMPRA_ID INT,
  DESCUENTO_COMPRA_CODIGO DECIMAL(19,0),
  DESCUENTO_COMPRA_VALOR DECIMAL(18,2),
  PRIMARY KEY (COMPRA_DESCUENTO_ID)
);

CREATE TABLE VARIANTE (
  VARIANTE_ID_CODIGO INT,
  PRODUCTO_VARIANTE VARCHAR,
  PRODUCTO_TIPO_VARIANTE VARCHAR,
  PRIMARY KEY (VARIANTE_ID_CODIGO)
);


CREATE TABLE TIPO_VARIANTE (
  TIPO_VARIANTE_ID INT,
  PRODUCTO_VARIANTE_CODIGO INT,
  PRIMARY KEY (TIPO_VARIANTE_ID)
);

--chequear, PK
CREATE TABLE PRODUCTO_X_VARIANTE_X_COMPRA (
  PRODUCTO_X_VAR_ID DECIMAL(18,2),
  COMPRA_ID DECIMAL(19,0),
  PROD_CANTIDAD DECIMAL(18,0),
  PRODUCTO_VARIANTE_PRECIO DECIMAL(18,2),
  PRIMARY KEY (PRODUCTO_X_VAR_ID),
  PRIMARY KEY (COMPRA_ID)
);


CREATE TABLE COMPRA  (
  COMPRA_ID DECIMAL(19,0),
  PROVEEDOR_ID INT,
  COMPRA_MEDIO_PAGO INT,
  DESCUENTO_COMPRA_ID INT,
  COMPRA_FECHA DATE,
  COMPRA_TOTAL DECIMAL(18,2),
  PRIMARY KEY (COMPRA_ID)
);

CREATE TABLE PROVEEDOR (
  PROVEEDOR_ID INT,
  PROVEEDOR_RAZON_SOCIAL NVARCHAR(50),
  PROVEEDOR_CUIT NVARCHAR(50),
  PROVEEDOR_DOMICILIO NVARCHAR(50),
  PROVEEDOR_MAIL NVARCHAR(50),
  PROVEEDOR_LOCALIDAD_ID INT,
  PRIMARY KEY (PROVEEDOR_ID)
);

CREATE TABLE MEDIO_PAGO (
  MEDIO_PAGO_ID INT,
  MEDIO_PAGO_DESCRIPCION VARCHAR,
  PRIMARY KEY (MEDIO_PAGO_ID)
);

CREATE TABLE PROVINCIA (
  PROVINCIA_ID INT,
  PROVINCIA_NOMBRE NVARCHAR(255),
  PRIMARY KEY (PROVINCIA_ID)
);

CREATE TABLE PRODUCTO_X_VARIANTE (
  PRODUCTO_ID DECIMAL(18,2),
  TIPO_VARIANTE_ID DECIMAL(19,0),
  PRIMARY KEY (PRODUCTO_ID),
  PRIMARY KEY (TIPO_VARIANTE_ID) 
);
/*
Esta tiene como FK a  PRODUCTO_ID Y A TIPO_VARIANTE_ID
*/

CREATE TABLE MEDIO_PAGO_VENTAS (
  MEDIO_PAGO_ID INT,
  VENTA_ID INT,
  MEDIO_DE_PAGO_COSTO_VENTAS DECIMAL(18,2),
  PRIMARY KEY (MEDIO_PAGO_ID)
);



CREATE TABLE CATEGORIA (
  CATEGORIA_ID INT,
  PRODUCTO_CATEGORIA VARCHAR,
  PRIMARY KEY (CATEGORIA_ID)
);

CREATE TABLE MARCA (
  MARCA_ID INT,
  PRODUCTO_MARCA VARCHAR,
  PRIMARY KEY (MARCA_ID)
);

CREATE TABLE DESCUENTO (
  DESCUENTO_ID INT,
  VENTA_DESCUENTO_CONCEPTO NVARCHAR(255),
  PRIMARY KEY (DESCUENTO_ID)
);


CREATE TABLE CANAL (
  CANAL_ID INT,
  CANAL_DESCRICION VARCHAR,
  PRIMARY KEY (CANAL_ID)
);

CREATE TABLE TIPO_CUPON (
  TIPO_CUPON_ID INT,
  CUPON_TIPO NVARCHAR(50),
  PRIMARY KEY (TIPO_CUPON_ID)
);

CREATE TABLE CUPON (
  CUPON_ID INT,
  CUPON_TIPO_ID INT,
  CUPON_CODIGO NVARCHAR(255),
  FECHA_CUPON_HASTA DATE,
  FECHA_CUPON_DESDE DATE,
  VENTA_CUPON_VALOR DECIMAL(18,2),
  PRIMARY KEY (CUPON_ID),

   
);

CREATE TABLE CUPON_X_VENTA  (
  VENTA_ID INT,
  CUPON_ID INT,
  VENTA_CUPON_IMPORTE DECIMAL(18, 2),
  PRIMARY KEY (CUPON_ID),
  PRIMARY KEY (VENTA_ID) 
);


CREATE TABLE CANAL_VENTA (
  CANAL_VENTA_ID INT,
  CANAL_ID VARCHAR,
  VENTA_CANAL_COSTO DECIMAL(18,2),
  PRIMARY KEY (CANAL_VENTA_ID)
);

CREATE TABLE VENTA (
  VENTA_ID (VENTA_CODIGO) DECIMAL(19,0),
  VENTA_MEDIO_PAGO_ID INT,
  VENTA_CLIENTE_ID INT,
  VENTA_CANAL_ID INT,
  PRODUCTO_ID DECIMAL(18,2),
  MEDIO_ENVIO_LOC_ID INT,
  VENTA_TOTAL DECIMAL(18,2),
  VENTA_FECHA DATETIME,
  PRIMARY KEY (VENTA_ID (VENTA_CODIGO))
);

CREATE TABLE MEDIO_ENVIO_X_LOCALIDAD (
  ID_ENVIO_X_LOC INT,
  LOCALIDAD_ID INT,
  MEDIO_ENVIO_ID VARCHAR,
  VENTA_ENVIO_PRECIO DECIMAL(18,2),
  PRIMARY KEY (ID_ENVIO_X_LOC)
);

CREATE TABLE MEDIO_ENVIO (
  ENVIO_ID INT,
  ENVIO_DESCRIPCION VARCHAR,
  PRIMARY KEY (ENVIO_ID)
);

CREATE TABLE CLIENTE (
  CLIENTE_ID INT,
  CLIENTE_NOMBRE INT,
  CLIENTE_APELLIDO NVARCHAR,
  CLIENTE_DNI INT,
  CLIENTE_DIRECCION NVARCHAR,
  CLIENTE_TELEFONO INT,
  CLIENTE_MAIL NVARCHAR,
  CLIENTE_FECHA_NAC DATE,
  CLIENTE_LOCALIDAD_ID INT,
  PRIMARY KEY (CLIENTE_ID)
);

CREATE TABLE LOCALIDAD (
  LOCALIDAD_ID INT,
  PROVINCIA_ID INT,
  LOCALIDAD_NOMBRE NVARCHAR(255),
  LOCALIDAD_CODIGO_POSTAL DECIMAL(18,0),
  PRIMARY KEY (LOCALIDAD_ID)
);

CREATE TABLE PRODUCTO (
  PRODUCTO_ID INT,
  PRODUCTO_NOMBRE VARCHAR,
  PRODUCTO_CODIGO NVARCHAR(50),
  PROD_DESCRIPCION NVARCHAR,
  MATERIAL_ID INT,
  MARCA_ID INT,
  CATEGORIA_ID INT,
  PRIMARY KEY (PRODUCTO_ID),
  KEY  (PRODUCTO_CODIGO)
);

CREATE TABLE PRODUCTO_X_VARIANTE_X_VENTA (
  PRODUCTO_X_VAR_ID DECIMAL(18,2),
  VENTA_ID INT,
  PROD_CANTIDAD DECIMAL(18,0),
  PRODUCTO_VARIANTE_PRECIO DECIMAL(18,2),
  PRIMARY KEY (PRODUCTO_X_VAR_ID),
  KEY  (PROD_CANTIDAD)
);

CREATE TABLE MATERIAL (
  MATERIAL_ID INT,
  PRODUCTO_MATERIAL VARCHAR,
  PRIMARY KEY (MATERIAL_ID)
);

CREATE TABLE DESCUENTO_X_VENTA (
  DESCUENTO_ID INT,
  VENTA_ID INT,
  VENTA_DESCUENTO_IMPORTE DECIMAL(18,2),
  KEY PK-FK (DESCUENTO_ID, VENTA_ID)
);

/*CREACIÓN DE PKS*/



/*CREACIÓN DE FKS*/

ALTER TABLE M_AL_CUBO.TABLA ADD CONSTRAINT FK_NOMBRE_FK FOREIGN KEY (TABLA_DONDE_ESTAR) REFERENCES M_AL_CUBO.AUTO
GO

ALTER TABLE M_AL_CUBO.DESCUENTO_COMPRA  ADD CONSTRAINT FK_COMPRA_ID FOREIGN KEY DESCUENTO_COMPRA REFERENCES M_AL_CUBO.COMPRA
GO


ALTER TABLE M_AL_CUBO.VARIANTE ADD CONSTRAINT FK_NOMBRE_FK FOREIGN KEY (TABLA_DONDE_ESTAR) REFERENCES M_AL_CUBO.AUTO
GO



ALTER TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE_X_COMPRA  ADD CONSTRAINT FK_PRODUCTO_X__VAR_ID  FOREIGN KEY PRODUCTO_X_VARIANTE REFERENCES M_AL_CUBO.AUTO
GO

ALTER TABLE M_AL_CUBO.PRODUCTO_X_VARIANTE_X_COMPRA  ADD CONSTRAINT FK_COMPRA_ID FOREIGN KEY COMPRA REFERENCES M_AL_CUBO.AUTO
GO
 
ALTER TABLE M_AL_CUBO.CUPON ADD CONSTRAINT FK_CUPON_TIPO_ID FOREIGN KEY TIPO_CUPON REFERENCES M_AL_CUBO.AUTO
GO 

ALTER TABLE M_AL_CUBO.CUPON_X_VENTA ADD CONSTRAINT FK_CUPON_ID FOREIGN KEY CUPON REFERENCES M_AL_CUBO.AUTO
GO

ALTER TABLE M_AL_CUBO.CUPON_X_VENTA ADD CONSTRAINT FK_NOMBRE_FK FOREIGN KEY VENTA REFERENCES M_AL_CUBO.AUTO
GO

--

/*CREAR FUNCIONES*/

CREATE FUNCTION M_AL_CUBO.FUNCION(/*PARÁMETROS @NOMBRE TIPO_DATO*/)
AS
BEGIN 
 
END 
GO 


/*CREAR PROCEDIMIENTOS*/


CREATE PROCEDURE M_AL_CUBO.MIGRAR_DESCUENTO_COMPRA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.DESCUENTO_COMPRA (COMPRA_ID, DESCUENTO_COMPRA_CODIGO, DESCUENTO_COMPRA_VALOR)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_COMPRA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.COMPRA (PROVEEDOR_ID, COMPRA_MEDIO_PAGO, DESCUENTO_COMPRA_ID, COMPRA_FECHA, COMPRA_TOTAL)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_PRODUCTO_X_VARIANTE_X_COMPRA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.PRODUCTO_X_VARIANTE_X_COMPRA (PRODUCTO_X_VAR_ID, COMPRA_ID, PROD_CANTIDAD, PRODUCTO_VARIANTE_PRECIO)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO


CREATE PROCEDURE M_AL_CUBO.MIGRAR_TIPO_VARIANTE
AS
BEGIN 

  INSERT INTO M_AL_CUBO.TIPO_VARIANTE (TIPO_VARIANTE_ID, PRODUCTO_VARIANTE_CODIGO)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_VARIANTE
AS
BEGIN 

  INSERT INTO M_AL_CUBO.VARIANTE (VARIANTE_ID_CODIGO, PRODUCTO_VARIANTE, PRODUCTO_TIPO_VARIANTE)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO


CREATE PROCEDURE M_AL_CUBO.PRODUCTO_X_VARIANTE
AS
BEGIN 

  INSERT INTO M_AL_CUBO.PRODUCTO_X_VARIANTE(PRODUCTO_ID, TIPO_VARIANTE_ID)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_PRODUCTO
AS
BEGIN 

  INSERT INTO M_AL_CUBO.PRODUCTO (PRODUCTO_ID, PRODUCTO_NOMBRE, PRODUCTO_CODIGO, PROD_DESCRIPCION, MATERIAL_ID, MARCA_ID, CATEGORIA_ID)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_PROVEEDOR
AS
BEGIN 

  INSERT INTO M_AL_CUBO.PROVEEDOR (PROVEEDOR_ID, PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_CUIT, PROVEEDOR_DOMICILIO, PROVEEDOR_MAIL, PROVEEDOR_LOCALIDAD_ID)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_MEDIO_PAGO
AS
BEGIN 

  INSERT INTO M_AL_CUBO.MEDIO_PAGO (MEDIO_PAGO_ID, MEDIO_PAGO_DESCRIPCION)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_LOCALIDAD
AS
BEGIN 

  INSERT INTO M_AL_CUBO.LOCALIDAD (LOCALIDAD_ID, PROVINCIA_ID, LOCALIDAD_NOMBRE, LOCALIDAD_CODIGO_POSTAL)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_PROVINCIA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.PROVINCIA(PROVINCIA_ID, PROVINCIA_NOMBRE)
  FROM GD_ESQUEMA.MAESTRA 
END 
GO


CREATE PROCEDURE M_AL_CUBO.MIGRAR_MEDIO_PAGO_VENTAS
AS
BEGIN 

  INSERT INTO M_AL_CUBO.MEDIO_PAGO_VENTAS (MEDIO_PAGO_ID, VENTA_ID, MEDIO_DE_PAGO_COSTO_VENTAS)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO


CREATE PROCEDURE M_AL_CUBO.MIGRAR_CLIENTE
AS
BEGIN 

  INSERT INTO M_AL_CUBO.CLIENTE (CLIENTE_ID, CLIENTE_NOMBHRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_DIRECCION, CLIENTE_TELEFONO, CLIENTE_MAIL, CLIENTE_FECHA_NAC, CLIENTE_LOCALIDAD_ID)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO




CREATE PROCEDURE M_AL_CUBO.MIGRAR_PRODUCTO_X_VARIANTE_X_VENTA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.PRODUCTO_X_VARIANTE_X_VENTA (PRODUCTO_X_VAR_ID, VENTA_ID, PROD_CANTIDAD, PRODUCTO_VARIANTE_PRECIO)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO


CREATE PROCEDURE M_AL_CUBO.MIGRAR_CATEGORIA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.CATEGORIA (CATEGORIA_ID, PRODUCTO_CATEGORIA)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO


CREATE PROCEDURE M_AL_CUBO.MIGRAR_MARCA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.MARCA (MARCA_ID, PRODUCTO_MARCA)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_MATERIAL
AS
BEGIN 

  INSERT INTO M_AL_CUBO.MATERIAL (MATERIAL_ID, PRODUCTO_MATERIAL)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_VENTA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.VENTA (VENTA_ID, VENTA_MEDIO_PAGO_ID, VENTA_CLIENTE_ID, VENTA_CANAL_ID, MEDIO_ENVIO_LOC_ID, VENTA_TOTAL, VENTA_FECHA)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_MEDIO_ENVIO_X_LOCALIDAD
AS
BEGIN 

  INSERT INTO M_AL_CUBO.MEDIO_ENVIO_X_LOCALIDAD (ID_ENVIO_X_LOC, LOCALIDAD_ID, MEDIO_ENVIO_ID, VENTA_ENVIO_PRECIO)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_MEDIO_ENVIO
AS
BEGIN 

  INSERT INTO M_AL_CUBO.MEDIO_ENVIO (ENVIO_ID, ENVIO_DESCRIPCION)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_CANAL_VENTA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.CANAL_VENTA (CANAL_VENTA_ID, CANAL_ID, VENTA_CANAL_COSTO)
  SELECT DISTINCT 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_CANAL
AS
BEGIN 

  INSERT INTO M_AL_CUBO.CANAL (CANAL_ID, CANAL_DESCRIPCION)
  SELECT distinct 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_CUPON_X_VENTA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.CUPON_X_VENTA (VENTA_ID, CUPON_ID, VENTA_CUPON_IMPORTE)
  SELECT distinct 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_CUPON
AS
BEGIN 

  INSERT INTO M_AL_CUBO.CUPON (CUPON_ID, CUPON_TIPO_ID, CUPON_CODIGO, FECHA_CUPON_HASTA, FECHA_CUPON_DESDE, VENTA_CUPON_VALOR)
  SELECT distinct 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_TIPO_CUPON
AS
BEGIN 

  INSERT INTO M_AL_CUBO.TIPO_CUPON (TIPO_CUPON_ID, CUPON_TIPO)
  SELECT distinct 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_DESCUENTO_X_VENTA
AS
BEGIN 

  INSERT INTO M_AL_CUBO.DESCUENTO_X_VENTA (DESCUENTO_ID, VENTA_ID, VENTA_DESCUENTO_IMPORTE)
  SELECT distinct 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO

CREATE PROCEDURE M_AL_CUBO.MIGRAR_DESCUENTO
AS
BEGIN 

  INSERT INTO M_AL_CUBO.DESCUENTO (DESCUENTO_ID, VENTA_DESCUENTO_CONCEPTO)
  SELECT distinct 
  FROM GD_ESQUEMA.MAESTRA 
END 
GO


/*EJECUTAR PROCEDIMIENTOS*/