USE GD2C2022
GO

-- DROP FK
IF OBJECT_ID('BI_M_AL_CUBO.FK_ENVIO_PROVINCIA_ID', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.DIMENSION_ENVIO DROP CONSTRAINT FK_ENVIO_PROVINCIA_ID
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_VENTA_ID_VENTA', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA DROP CONSTRAINT FK_HECHO_VENTA_ID_VENTA
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_VENTA_ID_PRODUCTO', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA DROP CONSTRAINT FK_HECHO_VENTA_ID_PRODUCTO
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_VENTA_ID_MEDIO_PAGO', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA DROP CONSTRAINT FK_HECHO_VENTA_ID_MEDIO_PAGO
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_VENTA_ID_TIEMPO', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA DROP CONSTRAINT FK_HECHO_VENTA_ID_TIEMPO
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_VENTA_ID_CLIENTE', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA DROP CONSTRAINT FK_HECHO_VENTA_ID_CLIENTE
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_VENTA_ID_RANGO_EDAD', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA DROP CONSTRAINT FK_HECHO_VENTA_ID_RANGO_EDAD
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_VENTA_ID_CANAL_VENTA', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA DROP CONSTRAINT FK_HECHO_VENTA_ID_CANAL_VENTA
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_VENTA_ID_ENVIO', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA DROP CONSTRAINT FK_HECHO_VENTA_ID_ENVIO
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_DESCUENTO_ID_VENTA', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_DESCUENTO DROP CONSTRAINT FK_HECHO_DESCUENTO_ID_VENTA
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_DESCUENTO_ID_DESCUENTO', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_DESCUENTO DROP CONSTRAINT FK_HECHO_DESCUENTO_ID_DESCUENTO
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_COMPRA_ID_COMPRA', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_COMPRA DROP CONSTRAINT FK_HECHO_COMPRA_ID_COMPRA
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_COMPRA_ID_PRODUCTO', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_COMPRA DROP CONSTRAINT FK_HECHO_COMPRA_ID_PRODUCTO
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_COMPRA_ID_PROVEEDOR', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_COMPRA DROP CONSTRAINT FK_HECHO_COMPRA_ID_PROVEEDOR
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_DESCUENTO_ID_DESCUENTO', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_COMPRA DROP CONSTRAINT FK_HECHO_DESCUENTO_ID_DESCUENTO
GO

IF OBJECT_ID('BI_M_AL_CUBO.FK_HECHO_COMPRA_ID_TIEMPO', 'F') IS NOT NULL
  ALTER TABLE BI_M_AL_CUBO.HECHO_COMPRA DROP CONSTRAINT FK_HECHO_COMPRA_ID_TIEMPO
GO

-- DROPS DE TABLAS
IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_CANAL_VENTA', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_CANAL_VENTA
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_PROVINCIA', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_PROVINCIA
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_ENVIO', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_ENVIO
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_CLIENTE', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_CLIENTE
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_MEDIO_PAGO', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_MEDIO_PAGO
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_RANGO_EDAD', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_RANGO_EDAD
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_PRODUCTO', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_PRODUCTO
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_TIEMPO', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_TIEMPO
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_COSTO', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_COSTO
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_DESCUENTO', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_DESCUENTO
GO

IF OBJECT_ID('BI_M_AL_CUBO.DIMENSION_PROVEEDOR', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.DIMENSION_PROVEEDOR
GO

IF OBJECT_ID('BI_M_AL_CUBO.HECHO_VENTA', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.HECHO_VENTA
GO

IF OBJECT_ID('BI_M_AL_CUBO.HECHO_DESCUENTO', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.HECHO_DESCUENTO
GO

IF OBJECT_ID('BI_M_AL_CUBO.HECHO_COMPRA', 'U') IS NOT NULL
    DROP TABLE BI_M_AL_CUBO.HECHO_COMPRA
GO

--DROP ESQUEMA
IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'BI_M_AL_CUBO')
  DROP SCHEMA BI_M_AL_CUBO
GO

-- CREO ESQUEMA
CREATE SCHEMA BI_M_AL_CUBO
GO

-- CREACION DE TABLAS

CREATE TABLE BI_M_AL_CUBO.DIMENSION_CANAL_VENTA(
	CANAL_VENTA_ID INT IDENTITY(1,1) PRIMARY KEY,
	CANAL_DESC NVARCHAR(255),
	CANAL_COSTO DECIMAL(18,2)
)
GO

CREATE TABLE BI_M_AL_CUBO.DIMENSION_PROVINCIA(
	PROVINCIA_ID INT IDENTITY(1,1) PRIMARY KEY,
	PROVINCIA_NOMBRE NVARCHAR(255)
)
GO

CREATE TABLE BI_M_AL_CUBO.DIMENSION_ENVIO(
	ENVIO_ID INT IDENTITY(1,1) PRIMARY KEY,
	PROVINCIA_ID INT,
	LOCALIDAD_NOMBRE NVARCHAR(255),
	LOCALIDAD_CODIGO DECIMAL(18,2),
	ENVIO_DETALLE NVARCHAR(255),
	ENVIO_PRECIO DECIMAL(18,2)
)
GO

CREATE TABLE BI_M_AL_CUBO.DIMENSION_CLIENTE(
	CLIENTE_ID INT IDENTITY(1,1) PRIMARY KEY,
	CLIENTE_NOMBRE NVARCHAR(255),
	CLIENTE_APELLIDO NVARCHAR(255),
	CLIENTE_DNI INT,
	CLIENTE_DIRECCION NVARCHAR(255),
	CLIENTE_TELEFONO INT,
	CLIENTE_MAIL NVARCHAR(255),
	CLIENTE_FECHA_NAC DATE,
);
GO

CREATE TABLE BI_M_AL_CUBO.DIMENSION_MEDIO_PAGO(
	MEDIO_PAGO_ID INT IDENTITY (1,1) PRIMARY KEY ,
	MEDIO_PAGO_DESCRIPCION NVARCHAR(255)
);
GO

CREATE TABLE BI_M_AL_CUBO.DIMENSION_RANGO_EDAD(
	RANGO_EDAD_ID INT IDENTITY (1,1) PRIMARY KEY ,
	RANGO_EDAD_DESCRIPCION NVARCHAR(255)
);
GO

CREATE TABLE BI_M_AL_CUBO.DIMENSION_PRODUCTO(
	PRODUCTO_ID INT IDENTITY(1,1) PRIMARY KEY,
	PRODUCTO_NOMBRE NVARCHAR(255),
	PRODUCTO_CODIGO NVARCHAR(50),
	DESCRIPCION_PROD NVARCHAR(255),
);
GO

CREATE TABLE BI_M_AL_CUBO.DIMENSION_TIEMPO(
	TIEMPO_ID INT IDENTITY(1,1) PRIMARY KEY,
	TIEMPO_ANIO INT,
	TIEMPO_MES INT
);
GO

CREATE TABLE BI_M_AL_CUBO.DIMENSION_DESCUENTO(
	DESCUENTO_ID INT IDENTITY(1,1) PRIMARY KEY,
	DESCUENTO_CONCEPTO NVARCHAR(255)
);
GO

CREATE TABLE BI_M_AL_CUBO.DIMENSION_PROVEEDOR(
	PROVEEDOR_ID INT IDENTITY (1,1) PRIMARY KEY,
	PROVEEDOR_RAZON_SOCIAL NVARCHAR(50),
	PROVEEDOR_CUIT NVARCHAR(50),
	PROVEEDOR_DOMICILIO NVARCHAR(50),
	PROVEEDOR_MAIL NVARCHAR(50),
);
GO

CREATE TABLE BI_M_AL_CUBO.HECHO_VENTA(
	ID_VENTA INT,
	ID_PRODUCTO DECIMAL(18,2),
	ID_MEDIO_PAGO INT,
	ID_TIEMPO INT,
	ID_CLIENTE INT,
	ID_RANGO_EDAD INT,
	ID_CANAL_VENTA INT,
	ID_ENVIO INT,
	VENTA_TOTAL DECIMAL(18,2),
	UNIDADES DECIMAL(18,2)
	PRIMARY KEY(ID_VENTA, ID_PRODUCTO, ID_MEDIO_PAGO, ID_TIEMPO, ID_CLIENTE, ID_RANGO_EDAD, ID_CANAL_VENTA, ID_ENVIO)
);
GO

CREATE TABLE BI_M_AL_CUBO.HECHO_DESCUENTO(
	ID_VENTA INT,
	ID_DESCUENTO INT,
	DESCUENTO_IMPORTE DECIMAL(18,2)
	PRIMARY KEY (ID_VENTA, ID_DESCUENTO)
);
GO

CREATE TABLE BI_M_AL_CUBO.HECHO_COMPRA(
	ID_COMPRA INT,
	ID_PRODUCTO DECIMAL(18,2),
	ID_PROVEEDOR INT, 
	ID_TIEMPO INT,
	COMPRA_TOTAL DECIMAL(18,2),
	UNIDADES DECIMAL(18,2)
	PRIMARY KEY (ID_COMPRA, ID_PRODUCTO, ID_PROVEEDOR, ID_TIEMPO)
);
GO

CREATE TABLE BI_M_AL_CUBO.HECHO_COSTO(
	ID_VENTA INT IDENTITY(1,1) PRIMARY KEY,
	ENVIO_COSTO DECIMAL(18,2),
	CANAL_VENTA_COSTO DECIMAL(18,2)
);
GO

-- FK

--ENV
ALTER TABLE BI_M_AL_CUBO.DIMENSION_ENVIO ADD CONSTRAINT FK_ENVIO_PROVINCIA_ID FOREIGN KEY (PROVINCIA_ID) REFERENCES BI_M_AL_CUBO.COMPRA(PROVINCIA_ID)
GO
--VENT
ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA ADD CONSTRAINT FK_HECHO_VENTA_ID_VENTA FOREIGN KEY (ID_VENTA) REFERENCES BI_M_AL_CUBO.HECHO_VENTA(ID_VENTA)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA ADD CONSTRAINT FK_HECHO_VENTA_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES BI_M_AL_CUBO.DIMENSION_PRODUCTO(PRODUCTO_ID)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA ADD CONSTRAINT FK_HECHO_VENTA_ID_MEDIO_PAGO FOREIGN KEY (ID_MEDIO_PAGO) REFERENCES BI_M_AL_CUBO.DIMENSION_MEDIO_PAGO(MEDIO_PAGO_ID)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA ADD CONSTRAINT FK_HECHO_VENTA_ID_TIEMPO FOREIGN KEY (ID_TIEMPO) REFERENCES BI_M_AL_CUBO.DIMENSION_TIEMPO(TIEMPO_ID)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA ADD CONSTRAINT FK_HECHO_VENTA_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES BI_M_AL_CUBO.DIMENSION_CLIENTE(CLIENTE_ID)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA ADD CONSTRAINT FK_HECHO_VENTA_ID_RANGO_EDAD FOREIGN KEY (ID_RANGO_EDAD) REFERENCES BI_M_AL_CUBO.DIMENSION_RANGO_EDAD(RANGO_EDAD_ID)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA ADD CONSTRAINT FK_HECHO_VENTA_ID_CANAL_VENTA FOREIGN KEY (ID_CANAL_VENTA) REFERENCES BI_M_AL_CUBO.DIMENSION_CANAL_VENTA(CANAL_VENTA_ID)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_VENTA ADD CONSTRAINT FK_HECHO_VENTA_ID_ENVIO FOREIGN KEY (ID_ENVIO) REFERENCES BI_M_AL_CUBO.DIMENSION_ENVIO(ENVIO_ID)
GO

--DESC
ALTER TABLE BI_M_AL_CUBO.HECHO_DESCUENTO ADD CONSTRAINT FK_HECHO_DESCUENTO_ID_VENTA FOREIGN KEY (ID_VENTA) REFERENCES BI_M_AL_CUBO.HECHO_DESCUENTO(ID_VENTA)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_DESCUENTO ADD CONSTRAINT FK_HECHO_DESCUENTO_ID_DESCUENTO FOREIGN KEY (ID_DESCUENTO) REFERENCES BI_M_AL_CUBO.DIMENSION_DESCUENTO(DESCUENTO_ID)
GO

--COMP
ALTER TABLE BI_M_AL_CUBO.HECHO_COMPRA ADD CONSTRAINT FK_HECHO_COMPRA_ID_COMPRA FOREIGN KEY (ID_COMPRA) REFERENCES BI_M_AL_CUBO.HECHO_COMPRA(ID_COMPRA)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_COMPRA ADD CONSTRAINT FK_HECHO_COMPRA_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES BI_M_AL_CUBO.DIMENSION_PRODUCTO(PRODUCTO_ID)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_COMPRA ADD CONSTRAINT FK_HECHO_COMPRA_ID_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES BI_M_AL_CUBO.DIMENSION_PROVEEDOR(PROVEEDOR_ID)
GO

ALTER TABLE BI_M_AL_CUBO.HECHO_COMPRA ADD CONSTRAINT FK_HECHO_COMPRA_ID_TIEMPO FOREIGN KEY (ID_TIEMPO) REFERENCES BI_M_AL_CUBO.DIMENSION_TIEMPO(TIEMPO_ID)
GO